# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements-test.txt" }}-{{ checksum "setup.py" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install mariadb
          command: |
            sudo apt install mariadb-server

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements-test.txt
            pip install -e .[tests]

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements-test.txt" }}-{{ checksum "setup.py" }}

      # run tests!
      - run:
          name: run tests
          command: |
            python3 --version
            mysqld --version
            . venv/bin/activate
            py.test -vv -n 0 --showlocals --mysql-user circleci --cov src/pytest_mysql tests

      - run:
          name: coveralls
          command: |
            pip install coveralls
            coveralls

      - store_artifacts:
          path: test-reports
          destination: test-reports