name: Run linters

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    uses: fizyk/actions-reuse/.github/workflows/linters-python.yml@v1.6.4
    with:
      pipenv: true
      pipenv-install-options: "--skip-lock"
