name: Run tests

on:
  push:
    branches: [ master ]
    paths:
      - '**.py'
      - .github/workflows/tests.yml
      - requirements-test.txt
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: [3.7, 3.8, 3.9, pypy-3.7-v7.3.3]
    env:
      OS: ubuntu-latest
      PYTHON: ${{ matrix.python-version }}
    # Service containers to run with `container-job`

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install MySQL
      run: |
        sudo apt-get install mysql-server
        mysqld --version
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-test.txt
    - name: Run test
      run: |
        pytest -n 0 --cov-report=xml
    - name: Run xdist test
      run: |
        pytest -n 1 --cov-report=xml:coverage-xdist.xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        files: ./coverage.xml, ./coverage-xdist.xml
        flags: linux,mysql
        env_vars: OS, PYTHON
        fail_ci_if_error: true
