name: Run tests on MySQL

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests-mysql-linux:
    uses: ./.github/workflows/tests-mysql-linux.yml
    with:
      mysql: "8.4"
      python-versions: '["3.9", "3.10", "3.11", "3.12", "3.13", "pypy-3.10"]'

  tests-mysql-linux_8:
    needs: [ tests-mysql-linux ]
    uses: ./.github/workflows/tests-mysql-linux.yml
    with:
      mysql: "8.0"
      python-versions: '["3.11", "3.12", "3.13"]'

  tests-mariadb-linux-11:
    needs: [ tests-mysql-linux ]
    uses: ./.github/workflows/tests-mariadb-linux.yml
    with:
      mariadb: "11.4"
      python-versions: '["3.11", "3.12", "3.13"]'

  tests-mariadb-linux-10_11:
    needs: [ tests-mariadb-linux-11 ]
    uses: ./.github/workflows/tests-mariadb-linux.yml
    with:
      mariadb: 10.11
      python-versions: '["3.12", "3.13"]'

  tests-mysql-macosx:
    runs-on: macos-latest
    needs: [tests-mysql-linux]
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    env:
      OS: macos-latest
      PYTHON: ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v4
    - uses: ankane/setup-mysql@v1
      with:
        mysql-version: 8.4
    - name: Check MySQL Version
      run: mysqld --version
    - name: Run test
      uses: fizyk/actions-reuse/.github/actions/pipenv@v2.6.0
      with:
        python-version: ${{ matrix.python-version }}
        command: pytest -n 0 -k "not mysqlnoproc" --cov-report=xml --mysql-user=root --basetemp=/tmp/pytest_mysql
        cache: false

  tests-mariadb-macosx:
    runs-on: macos-latest
    needs: [tests-mysql-macosx, tests-mariadb-linux-11]
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.13"]
    env:
      OS: macos-latest
      PYTHON: ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v4
    - uses: ankane/setup-mariadb@v1
      with:
        mariadb-version: "11.4"
    - name: Check MySQL Version
      run: mysqld --version
    - name: Run test
      uses: fizyk/actions-reuse/.github/actions/pipenv@v2.6.0
      with:
        python-version: ${{ matrix.python-version }}
        command: pytest --mysql-user=$USER -n 0 -k "not mysqlnoproc" --cov-report=xml --basetemp=/tmp/pytest_mysql
        cache: false
